const router= require('express').Router();
const authentication= require('../controller/authentication');
const userController=require('../controller/userController');
const appointmentController=require('../controller/appointmentController');
router.route('/login').post(authentication.login);
router.route('/isLoggedIn').get(authentication.protect,(req,res)=>{res.status(200).json({user:req.user})});
router.route('/logout').get(authentication.logout);
router.route('/sendRecoverEmail').post(userController.sendRecoverEmail);
router.route('/verifyCode').post(authentication.verifyCode);
router.route('/resetPassword').post(authentication.protectVerifyCode, authentication.setUpNewPassword);
router.route('/getPatientsDashboard').get(authentication.protect,userController.getDashboard);
router.route('/userInfo').get(authentication.protect,userController.userInfo);
router.route('/updateUserPhoto').post(authentication.protect,userController.uploadUserPhoto, userController.resizeUserPhoto,userController.updatedImagePath);
router.route('/changeUserInfo').patch(authentication.protect, userController.changeUserInfo);
router.route('/requestAppointment').post(authentication.protect,userController.uploadArrayPhoto, appointmentController.acceptFiles);
router.route('/getAllPreAppointments').get(authentication.protect,authentication.restrictTo('dispatcher'), appointmentController.getAllPreAppointments);
router.route('/getAllCancelledAppointments').get(authentication.protect,authentication.restrictTo('admin','dispatcher'),appointmentController.getAllCancelledAppointments);
router.route('/getPreAppointmentInfo/:preAppointmentId').get(authentication.protect,appointmentController.getPreAppoinment);
router.route('/cancelAppointment/:appointmentId').get(authentication.protect, appointmentController.cancelAppointment);
router.route('/deleteAppointment/:appointmentId').get(authentication.protect,authentication.restrictTo('admin','dispatcher'),appointmentController.deleteAppointment);
router.route('/closeAppointment/:appointmentId').post(authentication.protect, authentication.restrictTo('admin','doctor'),userController.uploadArrayPhoto, appointmentController.closeAppointment);
router.route('/getPreAppointmentId/:preAppointmentId').get(authentication.protect,appointmentController.getPreAppoinmentId );
module.exports=router;